version: 2
 
models:
  - name: fact_order
    columns:
      - name: salesorderdetailid 
        description: The primaty key key.
        tests:
          - not_null
 
      - name: creditcardid  
        description: The customer foreign key
        tests:
          - relationships:
              to: ref('dim_customer')
              field: creditcardid  
